version: '2'

services:
  app:
    image: golang:1.8-alpine
    container_name: ViessmannScraper
    volumes:
      - .:/go/src/
    working_dir: /go/src/
    command: go run ViessmannScraper.go -address=raspberrypi-2 -port=3002
