version: '2'

services:
  app:
    build: .
    container_name: ViessmannScraper
    volumes:
      - .:/go/src/
    working_dir: /go/src/
    command: go run ViessmannScraper.go -address=raspberrypi-2 -port=3002
    environment:
      INFLUX_URL: http://snes:8086
      INFLUX_USER: root
      INFLUX_PASS: root
